spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunyi?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: 1234

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  config: classpath:logback-spring.xml
  pattern:
    console: "%date [%level] [%thread] %logger{60} [%file : %line] %msg%n"
    file: "%date [%level] [%thread] %logger{60} [%file : %line] %msg%n"
  level:
    root: info
    net.yunyi.back.persistence.mapper: debug
  file:
    path: logs/
server:
  port: 8090
tencent:
  secret:
    id: ${secretID}
    key: ${secretKey}
    tempID: ${templateID}
    appId: ${appID}
    sign: ${sign}